# filename: roles/configure/etcd/tasks/test.yml
---

- name: Wait for port 2379 to listen
  wait_for:
    port: 2379
    delay: 120

- name: Get etcd nodes
  command: etcdctl ls
  register: etcd_nodes
  changed_when: false
  until: "'/coreos.com' in etcd_nodes.stdout"
  retries: 10
  delay: 10
